### ISSUE TITLE
Basic curl put command failing

### ISSUE THREAD

**Issue by ronniec95** [njaard/sonnerie#23]
Trying to run the example curl command fails

curl -X PUT http://localhost:5555/ --data-binary 'fibonacci 2020-01-07T00:00:00 u 13'
**parsing timestamp invalid digit found in string**

This is running the basic sonnerie-serve

Adding/retrieving data using sonnerie read / add works fine

The root cause appears to be that in sonnerie-serve you parse i64 nanosecond timestamps on line 138

```
                let ts: Timestamp = timestamp
                    .parse()
                    .map_err(|e| format!("parsing timestamp {}", e))?;

```
where Timestamp is ```pub type Timestamp = u64```

I assume the UNIX_EPOCH is an opaque value to the client, though sending timestamps through like that does indeed work.

**Comment by ronniec95** [comment]
To close the issue, update the readme to tell the user that timestamps need to be specified in nanoseconds since 1/1/1970 when using http or update the code so it matches the same format as the local binary

**Comment by njaard** [comment]
I have updated the readme, thank you for reporting.
