### ISSUE TITLE
ToRecord for String?

### ISSUE THREAD

**Issue by ettom** [njaard/sonnerie#28]
Hi, I'd like to write a function like this:
```rust
pub async fn write(
    key: String,
    values: impl RecordBuilder + std::marker::Send + 'static,
) -> Result<()> {
    let handle: JoinHandle<Result<()>> = tokio::task::spawn_blocking(move || {
        let db = std::path::Path::new(DB_PATH);

        let mut transaction = CreateTx::new(db)?;

        let timestamp = chrono::Utc::now();
        let naive_utc: NaiveDateTime = timestamp.naive_utc();

        transaction.add_record(&key, naive_utc, values)?;
        transaction.commit()?;
        Ok(())
    });

    handle.await?
}
```

The problem is that as far as I can tell, this function isn't callable with a Record containing a (non-static) `&str`, as it won't live long enough. E.g:
```rust
let foo = String::from("foo");
db::write("bar".to_owned(), sonnerie::record(foo.as_str())).await;
```

Is there an obvious solution to this issue that I'm missing? Would you consider adding a `ToRecord` impl for `String`?

**Comment by njaard** [comment]
Hi @ettom, thanks for writing!

I think a `ToRecord` for `String` is reasonable, especially since you have an obvious use-case.

If you'd like that, I will happily apply your pull request :)

What you can also do is call `RecordBuilder::store(&self, &mut Vec<u8>)`, and then move the `Vec<u8>` into the `tokio::task::spawn_blocking`. Then you would call `https://docs.rs/sonnerie/latest/sonnerie/struct.CreateTx.html#method.add_record_raw`.

**Comment by ettom** [comment]
> What you can also do is call `RecordBuilder::store(&self, &mut Vec<u8>)`, and then move the `Vec<u8>` into the `tokio::task::spawn_blocking`. Then you would call [`CreateTx::add_record_raw`](https://docs.rs/sonnerie/latest/sonnerie/struct.CreateTx.html#method.add_record_raw)

I tried this but couldn't really make it work. What exactly do I do with the `Vec<u8>` that I get from `store()`?

```rust
fn main() -> Result<()> {
    let foo = Foo {
        bar: "bar".to_string(),
        baz: 42,
    };

    let record = sonnerie::record(&*foo.bar).add(foo.baz);

    let mut buf = Vec::new();
    record.store(&mut buf);

    let mut fmt = compact_str::CompactString::default();
    record.format_str(&mut fmt);

    let row = sonnerie::row_format::parse_row_format(&fmt);

    let mut buf2 = Vec::new();
    row.to_stored_format(1.1e18 as u64, ???, &mut buf2).unwrap();

    let mut transaction = CreateTx::new(std::path::Path::new(DB_PATH))?;
    transaction.add_record_raw("foos", &fmt, &buf2)?;
    transaction.commit()?;

    Ok(())
}
```

**Comment by njaard** [comment]
You should be able to use `fmt` and `buf` directly into `add_record_raw`. The stuff you do with `row` and `buf2` aren't necessary.

**Comment by ettom** [comment]
In this case, how do I specify the timestamp?

**Comment by njaard** [comment]
Argh, you're right.

I'm trying to move away from the `formatted` module, so I'll just merge your PR. Hopefully that's enough!

**Comment by njaard** [comment]
@ettom ok, I just released a new version. I hope that's good. I also created a new issue (https://github.com/njaard/sonnerie/issues/30) just to track our difficulty with add_record_raw

**Comment by ettom** [comment]
Thanks a lot!
