### ISSUE TITLE
Is it possible to have a column containing a string?

### ISSUE THREAD

**Issue by Morsicus** [njaard/sonnerie#4]
Hey! 

Thanks for you work. Very interesting to read/learn about. 

I've a question, is it possible to have a column containing a String? It will behave as a "tag" or "label".

**Comment by njaard** [comment]
Hello Morsicus, I just published a total rewrite of sonnerie. The feature still doesn't exist, but at least is possible now! I may get to implementing in the near future.

**Comment by njaard** [comment]
@Morsicus You may be pleased to learn that the master version now supports string columns!

I'd love you to play with it before I make a release.

**Comment by njaard** [comment]
Just published 0.5.4 to crates.io
