### ISSUE TITLE
Better iterator API

### ISSUE THREAD

**Issue by zimond** [njaard/sonnerie#6]
Can we have ranged timestamp select API or at least Double ended iterators to fetch records from the newest to oldest?

**Comment by njaard** [comment]
Hi zimond. double-ended iterators are possible, but be aware that a single series (any key) needs to fit in memory, so maybe it's not extremely useful. I will add it to my plan.

(allowing series that wouldn't fit in memory is on my TODO list also).

**Comment by zimond** [comment]
A common use case for time series db is to save logs. And usually you want to get some latest logs. How could I do that with sonnerie? Maybe I'm missing something?

**Comment by njaard** [comment]
Maybe Sonnerie isn't too well suited for that.

If you just build a single timeseries (a single key) from every log event, then the key will grow large and not fit in memory. You could partition the logs into various names, but that might be more work than it's worth.

**Comment by zimond** [comment]
Thanks for the explanation
