### ISSUE TITLE
This crate seems good, but why not cargo fmt

### ISSUE THREAD

**Issue by uuhan** [njaard/sonnerie#9]
This crate satifies my need for an embedded time-series database and I'am quite interesting to look inside the implementation of this crate.

But the code styling seems not quite good for reading. Maybe it's good to 

```bash
cargo fmt
```

**Comment by nsauzede** [comment]
I second that request : standard cargo fromatting would help external contributions to this repo, IMHO..

**Comment by njaard** [comment]
Done in the major new version branch, split-keys

**Comment by nsauzede** [comment]
Great !
But I see that it's been done in a not-up-to-date branch; won't that be harder to rebase it in master ?

**Comment by njaard** [comment]
I've been working on that alternate branch for a while and they've diverged a bit. I'm merging right now

**Comment by nsauzede** [comment]
I see.
Good job

**Comment by njaard** [comment]
No, you're right, I just did a forced push to `split-keys` to fix the situation.
